# Generated by Django 2.2.5 on 2021-01-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210114_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='adress',
            new_name='address',
        ),
    ]
